apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: spark-role
  namespace: {{ namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
