from setuptools import setup

setup(
    name="pyspark",
    version="3.1.2",
    description="Apache Spark Python API (/opt/spark/python)",
    author="Spark Developers",
    author_email="dev@spark.apache.org",
    url="https://github.com/apache/spark/tree/master/python",
    packages=[
        "pyspark",
        "pyspark.cloudpickle",
        "pyspark.mllib",
        "pyspark.mllib.linalg",
        "pyspark.mllib.stat",
        "pyspark.ml",
        "pyspark.ml.linalg",
        "pyspark.ml.param",
        "pyspark.sql",
        "pyspark.sql.avro",
        "pyspark.sql.pandas",
        "pyspark.streaming",
        "pyspark.python.pyspark",
        "pyspark.resource",
    ],
    license="http://www.apache.org/licenses/LICENSE-2.0",
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Typing :: Typed",
    ],
)
